### ISSUE TITLE
官网上cronetEngine没有setHostResolver接口

### ISSUE THREAD

**Issue by chrisme22** [lizhangqu/chromium-net-for-android#2]
你好，官网上master分支没有这个接口，请问你这个是？
  .setHostResolver(new HostResolver() {
            @Override
            public List<InetAddress> resolve(String hostname) throws UnknownHostException {
                if (hostname == null)
                    throw new UnknownHostException("hostname == null");
                return Arrays.asList(InetAddress.getAllByName(hostname));
            }
        })

**Comment by hanpfei** [comment]
这个好像是我 fork 的 chromium net 的项目中， https://github.com/hanpfei/chromium-net ，加的用于类似像 HttpDns 这种场景的接口。
这个接口，允许应用程序自己定义 DNS 逻辑。自己定义的 DNS 逻辑实现这个接口，把 DNS 的结果返回给 chromium net。
https://github.com/hanpfei/chromium-net/blob/master/components/cronet/android/api/src/org/chromium/net/HostResolver.java。

**Comment by lizhangqu** [comment]
如上

**Comment by 10045125** [comment]
请问下，这个HostResolver测试有效果吗？

**Comment by hanpfei** [comment]
> 请问下，这个HostResolver测试有效果吗？

有效果啊，
