### ISSUE TITLE
gradle  编译时出错

### ISSUE THREAD

**Issue by blueberryCoder** [lizhangqu/chromium-net-for-android#6]
* What went wrong:
A problem occurred evaluating project ':cronet-api'.
> Failed to apply plugin [id 'android.publish']
   > you must config RELEASE_REPOSITORY_URL in properties. Like config project.ext.RELEASE_REPOSITORY_URL , add RELEASE_REPOSITORY_URL in gradle.properties or add RELEASE_REPOSITORY_URL in local.properties which locates on root project dir

**Comment by recnac-itna** [comment]
I encounter the same error. 老哥能帮忙看下吗

**Comment by lizhangqu** [comment]
在gradle.properties里加入几个空属性
RELEASE_REPOSITORY_URL=
